import { images } from "./content.ts";

export const workItems = [
  {
    type: "Procurement Service",
    title: "Customizable",
    summary: "A structured service presence that explains the procurement offer, working process, and route for tailored enquiries.",
    image: images.contactPlanning,
    websitePreview: false,
    scrollImage: undefined,
    packageName: "Advanced",
    url: undefined,
    addons: ["Website content planning", "Custom animation"],
    delivered: ["Procurement service website", "Enhanced SEO and analytics", "Structured request form"],
    outcome: "A clearer way for prospective customers to understand the service and request support.",
  },
  {
    type: "Bean Exporter",
    title: "Sein Htan Pin",
    summary: "A professional company presence that introduces the exporter, communicates its products, and gives trade partners a clear route to enquire.",
    image: "/images/projects/sein-htan-pin-preview.webp",
    websitePreview: true,
    scrollImage: "/images/projects/sein-htan-pin-preview.webp",
    packageName: "Hybrid",
    url: "https://seinhtanpin.com/",
    addons: ["Connected Presence"],
    delivered: ["Company profile website", "Product and export overview", "Trade enquiry details"],
    outcome: "A credible digital reference for buyers and potential business partners.",
  },
  {
    type: "Restaurant",
    title: "The Peak",
    summary: "A clear, mobile-first experience from discovering the restaurant to viewing its menu, location, and contact details.",
    image: "/images/projects/the-peak-homepage.png",
    websitePreview: true,
    scrollImage: "/images/projects/the-peak-preview.webp",
    packageName: "Basic Online",
    url: "https://taunggyihotel-thepeak-website.yetunkhine.workers.dev/thepeak/",
    addons: ["Website content planning", "Connected Presence"],
    delivered: ["Menu-led website", "CMS for regular updates", "Maps and contact flow"],
    outcome: "Essential dining information is easier to browse, update, and act on.",
  },
  {
    type: "Hotel",
    title: "Taunggyi Hotel",
    summary: "A welcoming hotel presence that makes accommodation details, location information, and the path to enquire easier to understand.",
    image: "/images/projects/taunggyi-hotel-homepage.png",
    websitePreview: true,
    scrollImage: "/images/projects/taunggyi-hotel-preview.webp",
    packageName: "Basic Online",
    url: "https://taunggyihotel-thepeak-website.yetunkhine.workers.dev/",
    addons: ["Connected Presence", "Website content planning"],
    delivered: ["Accommodation-led website", "Google Business Profile", "Guest enquiry flow"],
    outcome: "A clearer, more consistent journey from discovering the hotel to making contact.",
  },
] as const;

